name: Create a comment on new issue from workflow

on:
  issues:
    types: [opened, closed]

jobs:
  comment-with-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}' | jq
        shell: bash

      - name: Dump job context
        run: echo '${{ secrets.MY_TOKEN }}' | jq
        shell: bash

      