name: Create a comment on new issue from workflow

on:
  issues:
    types: [opened]

jobs:
  comment-with-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}' | jq
        shell: bash

     